# Hexo PaperMod Theme Configuration
# Converted from Hugo PaperMod theme

# Theme Information
theme_name: papermod
version: 1.0.0
description: A fast, clean, responsive Hexo theme based on Hugo PaperMod
author: Yongkang Yang
original_author: Aditya Telange
original_theme: https://github.com/adityatelange/hugo-PaperMod

# Features
features:
  darkmode: true
  search: true
  toc: true
  cover_image: true
  social_icons: true
  share_icons: true
  archive: true
  multilingual: true
  theme_toggle: true
  scroll_to_top: true

# Menu Configuration
menu:
  Home: /
  Archives: /archives/
  Categories: /categories/
  Tags: /tags/
  Search: /search/

# Social Icons
social:
  - icon: github
    url: https://github.com/yongkang-yang
    title: GitHub
  - icon: linkedin
    url: https://www.linkedin.com/in/yongkang-yang-0530a1205/
    title: LinkedIn
  - icon: rss
    url: https://yongkang-yang.github.io/atom.xml
    title: RSS

# Default cover image
defaultCover: /img/default-cover.jpg

# Site Settings
showReadingTime: true
showShareButtons: true
showPostNavLinks: true
showBreadCrumbs: true
showCodeCopyButtons: true
disableSpecial1stPost: false
disableScrollToTop: false
comments: false
hidemeta: false
hideSummary: false
showtoc: true
tocopen: false

# Internationalization
defaultContentLanguage: en
